/**
 * Market-aligned defaults for Soulmate9 (NSFW companion + portrait FLUX).
 * Aligned with: Free cheap SFW / Pro NSFW self-host / Image as token monetization.
 */
import type { AiModulesConfig } from './types';

export const AI_MODULES_SETTINGS_KEY = 'ai_modules';

export function createDefaultAiModules(): AiModulesConfig {
  const now = new Date().toISOString();

  return {
    version: 2,
    updated_at: now,
    endpoints: [
      {
        id: 'together-qwen35-9b',
        label: 'Together Qwen3.5 9B (Economy)',
        provider: 'together',
        model_id: 'Qwen/Qwen3.5-9B',
        api_base_url: 'https://api.together.xyz/v1',
        api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.85,
        max_tokens: 512,
        cost_per_1k_input: 0.0001,
        cost_per_1k_output: 0.0001,
        nsfw_capable: false,
        notes: 'Cheap SFW chat for free tier',
      },
      {
        id: 'dashscope-qwen-plus',
        label: 'Bailian Qwen-Plus (SFW Primary)',
        provider: 'dashscope',
        model_id: 'qwen-plus',
        api_base_url: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
        api_key_env: 'DASHSCOPE_API_KEY',
        temperature: 0.85,
        max_tokens: 1024,
        cost_per_1k_input: 0.00011,
        cost_per_1k_output: 0.00028,
        nsfw_capable: false,
        priority: 1,
        timeout_ms: 25000,
        retry_count: 1,
        circuit_breaker: { failure_threshold: 3, reset_ms: 60000 },
        capabilities: ['chat', 'classification'],
        quality_tier: 'standard',
        notes: 'Alibaba Bailian (DashScope) OpenAI-compatible. SFW only — content filter rejects NSFW with HTTP 400, fallback chain continues to RunPod.',
      },
      {
        id: 'together-qwen3-235b',
        label: 'Together Qwen3 235B-A22B (Quality)',
        provider: 'together',
        model_id: 'Qwen/Qwen3-235B-A22B-Instruct-2507-tput',
        api_base_url: 'https://api.together.xyz/v1',
        api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.85,
        max_tokens: 1536,
        cost_per_1k_input: 0.0002,
        cost_per_1k_output: 0.0006,
        nsfw_capable: false,
        notes: 'High quality SFW roleplay',
      },
      {
        id: 'runpod-qwen35-9b-abliterated',
        label: 'RunPod Qwen3.5 9B Abliterated (NSFW)',
        provider: 'runpod',
        model_id: 'soulmate-qwen35-9b-nsfw',
        api_base_url: null,
        api_base_env: 'RUNPOD_PRO_CHAT_URL',
        api_key_env: 'RUNPOD_VLLM_API_KEY',
        temperature: 0.9,
        max_tokens: 1024,
        cost_per_1k_input: 0,
        cost_per_1k_output: 0,
        nsfw_capable: true,
        notes: 'Uncensored NSFW RP · GPU second billing',
      },
      {
        id: 'runpod-qwen3-30b-roleplay',
        label: 'RunPod Qwen3 30B-A3B Roleplay (NSFW)',
        provider: 'runpod',
        model_id: 'soulmate-qwen3-30b-roleplay',
        api_base_url: null,
        api_base_env: 'RUNPOD_UNLIMITED_CHAT_URL',
        api_key_env: 'RUNPOD_VLLM_API_KEY',
        temperature: 0.9,
        max_tokens: 1536,
        cost_per_1k_input: 0,
        cost_per_1k_output: 0,
        nsfw_capable: true,
        priority: 5,
        timeout_ms: 60000,
        retry_count: 1,
        circuit_breaker: { failure_threshold: 3, reset_ms: 120000 },
        notes: 'Qwen3-30B-A3B MoE on 80GB A100. Cold start ~5min. Best NSFW quality for Unlimited.',
      },
      {
        id: 'together-kimi-k26', label: 'Together Kimi K2.6 (Long memory)', provider: 'together',
        model_id: 'moonshotai/Kimi-K2.6', api_base_url: 'https://api.together.xyz/v1', api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.8, max_tokens: 2048, cost_per_1k_input: 0.0012, cost_per_1k_output: 0.0045,
        nsfw_capable: false, capabilities: ['chat', 'long_context'], quality_tier: 'premium', priority: 30,
        timeout_ms: 45000, retry_count: 1, fallback_ids: ['together-qwen3-235b'], circuit_breaker: { failure_threshold: 3, reset_ms: 60000 },
      },
      {
        id: 'together-gpt-oss-20b', label: 'Together GPT-OSS 20B (Fallback)', provider: 'together',
        model_id: 'openai/gpt-oss-20b', api_base_url: 'https://api.together.xyz/v1', api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.8, max_tokens: 1024, cost_per_1k_input: 0.00005, cost_per_1k_output: 0.0002,
        nsfw_capable: false, capabilities: ['chat'], quality_tier: 'economy', priority: 90, timeout_ms: 30000,
      },
      {
        id: 'together-gpt-oss-120b', label: 'Together GPT-OSS 120B (Fallback)', provider: 'together',
        model_id: 'openai/gpt-oss-120b', api_base_url: 'https://api.together.xyz/v1', api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.8, max_tokens: 1536, cost_per_1k_input: 0.00015, cost_per_1k_output: 0.0006,
        nsfw_capable: false, capabilities: ['chat'], quality_tier: 'standard', priority: 90, timeout_ms: 35000,
      },      {
        id: 'together-qwen35-classifier',
        label: 'Together Qwen3.5 9B Classifier',
        provider: 'together',
        model_id: 'Qwen/Qwen3.5-9B',
        api_base_url: 'https://api.together.xyz/v1',
        api_key_env: 'TOGETHER_API_KEY',
        temperature: 0.15,
        max_tokens: 128,
        cost_per_1k_input: 0.0001,
        cost_per_1k_output: 0.0001,
        nsfw_capable: false,
        notes: 'Classification / short JSON tasks',
      },
      {
        id: 'flux-portrait',
        label: 'RunPod FLUX Portrait',
        provider: 'runpod',
        model_id: 'flux1-dev-fp8',
        api_base_url: null,
        api_key_env: 'RUNPOD_API_KEY',
        temperature: 0,
        max_tokens: 0,
        cost_per_1k_input: 0,
        cost_per_1k_output: 0,
        nsfw_capable: true,
        notes: 'ComfyUI FLUX image endpoint',
      },
      // ── OpenRouter NSFW fallback (uncensored models) ──
      {
        id: 'openrouter-lumimaid-9b',
        label: 'OpenRouter Lumimaid 9B (NSFW Fallback)',
        provider: 'openrouter',
        model_id: 'lumimaid-v02-9b',
        api_base_url: 'https://openrouter.ai/api/v1',
        api_key_env: 'OPENROUTER_API_KEY',
        temperature: 0.9,
        max_tokens: 1024,
        cost_per_1k_input: 0.0003,
        cost_per_1k_output: 0.0003,
        nsfw_capable: true,
        priority: 50,
        timeout_ms: 30000,
        retry_count: 1,
        fallback_ids: ['openrouter-noromaid-20b'],
        circuit_breaker: { failure_threshold: 3, reset_ms: 60000 },
        notes: 'Uncensored NSFW RP fallback when RunPod is down',
      },
      {
        id: 'openrouter-noromaid-20b',
        label: 'OpenRouter Noromaid 20B (NSFW Quality)',
        provider: 'openrouter',
        model_id: 'noromaid-20b',
        api_base_url: 'https://openrouter.ai/api/v1',
        api_key_env: 'OPENROUTER_API_KEY',
        temperature: 0.85,
        max_tokens: 1536,
        cost_per_1k_input: 0.0006,
        cost_per_1k_output: 0.0006,
        nsfw_capable: true,
        priority: 55,
        timeout_ms: 35000,
        retry_count: 1,
        circuit_breaker: { failure_threshold: 3, reset_ms: 60000 },
        notes: 'Higher quality NSFW RP via OpenRouter',
      },
      // ── RunPod DC2 (DISABLED: no GPU supply in US-TX-3) ──
      {
        id: 'runpod-dc2-qwen35-9b',
        label: 'RunPod DC2 Qwen3 (NSFW Backup)',
        provider: 'runpod',
        model_id: 'soulmate-qwen3-dc2',
        api_base_url: null,
        api_base_env: 'RUNPOD_DC2_CHAT_URL',
        api_key_env: 'RUNPOD_VLLM_API_KEY',
        temperature: 0.9,
        max_tokens: 1024,
        cost_per_1k_input: 0,
        cost_per_1k_output: 0,
        nsfw_capable: true,
        priority: 20,
        timeout_ms: 25000,
        retry_count: 1,
        health_status: 'disabled',
        circuit_breaker: { failure_threshold: 3, reset_ms: 90000 },
        notes: 'DISABLED: US-TX-3 no GPU. Enable when 32GB+ available.',
      },
    ],
    chat: {
      enabled: true,
      classifier_endpoint_id: 'dashscope-qwen-plus',
      complexity_threshold: 5,
      nsfw_min_intimacy: 3,
      nsfw_detection: 'keywords',
      // The current RunPod chat worker has a mismatched model/tokenizer and can
      // emit multilingual garbage. Keep it out of normal chat routing.
      fallback_endpoint_id: 'together-gpt-oss-20b',
      global_system_suffix:
        'Stay in character as the girlfriend. Never break role. Never claim to be an AI assistant. When the intimate/NSFW channel is active, lean into consensual adult desire with sensory detail and end replies with a hook that invites the next message. Refuse underage content. Match language rules (English sessions: English only, no Chinese).',
      tiers: {
        free: {
          sfw_endpoint_id: 'dashscope-qwen-plus', nsfw_endpoint_id: null,
          default_endpoint_id: 'dashscope-qwen-plus', complex_endpoint_id: 'dashscope-qwen-plus',
          fallback_endpoint_ids: ['together-qwen35-9b', 'together-gpt-oss-20b'], daily_cost_soft_limit_usd: 0.08,
          max_tokens: 512, context_messages: 10, daily_message_limit: 40, allow_nsfw: false,
        },
        basic: {
          sfw_endpoint_id: 'dashscope-qwen-plus', nsfw_endpoint_id: null,
          default_endpoint_id: 'dashscope-qwen-plus', complex_endpoint_id: 'dashscope-qwen-plus',
          fallback_endpoint_ids: ['together-qwen35-9b', 'together-gpt-oss-20b'], daily_cost_soft_limit_usd: 0.15,
          max_tokens: 768, context_messages: 16, daily_message_limit: 150, allow_nsfw: false,
        },
        pro: {
          sfw_endpoint_id: 'dashscope-qwen-plus',
          nsfw_endpoint_id: 'runpod-qwen35-9b-abliterated',
          default_endpoint_id: 'dashscope-qwen-plus', complex_endpoint_id: 'dashscope-qwen-plus',
          fallback_endpoint_ids: ['runpod-qwen35-9b-abliterated', 'openrouter-lumimaid-9b', 'together-qwen3-235b', 'together-gpt-oss-120b'], daily_cost_soft_limit_usd: 0.75,
          max_tokens: 1024,
          context_messages: 24,
          // Competitor-aligned Pro chat cap (not marketing "unlimited")
          daily_message_limit: 300,
          allow_nsfw: true,
        },
        unlimited: {
          sfw_endpoint_id: 'dashscope-qwen-plus',
          nsfw_endpoint_id: 'runpod-qwen3-30b-roleplay',
          default_endpoint_id: 'dashscope-qwen-plus', complex_endpoint_id: 'together-kimi-k26',
          fallback_endpoint_ids: ['runpod-qwen3-30b-roleplay', 'runpod-qwen35-9b-abliterated', 'openrouter-noromaid-20b', 'together-qwen3-235b', 'together-gpt-oss-120b'], daily_cost_soft_limit_usd: 2.5,
          max_tokens: 1536,
          context_messages: 40,
          // Unlimited chat (null = no daily cap); images/TTS remain cost levers
          daily_message_limit: null,
          allow_nsfw: true,
        },
      },
    },
    image: {
      enabled: true,
      runpod_endpoint_env: 'RUNPOD_ENDPOINT_ID',
      runpod_api_key_env: 'RUNPOD_API_KEY',
      // FLUX: empty/minimal negative preferred (long SD negatives → black frames)
      default_negative: '',
      free_daily_images: 3,
      // Images remain the main GPU cost lever; Free gets a small trial allowance.
      pro_daily_images: 10,
      unlimited_daily_images: 50,
      scenes: {
        girlfriend_portrait: {
          endpoint_id: 'flux-portrait',
          width: 768,
          height: 1152,
          steps: 14,
          cfg: 1.0,
          count: 2,
          token_cost: 0, // admin
          use_consistency_default: true,
          allow_llm_prompt_polish: true,
        },
        chat_selfie: {
          endpoint_id: 'flux-portrait',
          tier_endpoint_ids: { free: 'together-flux1-schnell', pro: 'runpod-flux2-klein-4b', unlimited: 'bfl-flux2-quality' },
          adult_endpoint_ids: { pro: 'runpod-flux2-klein-adult', unlimited: 'runpod-flux2-premium-adult' },
          fallback_endpoint_ids: ['runpod-flux2-klein-4b'],
          quality_tier: 'standard', reference_mode: 'multi', max_references: 3, adult_capable: true,
          retry_policy: { max_attempts: 2, lower_quality_on_retry: true, similarity_retry: true },
          width: 704,
          height: 960,
          steps: 12,
          cfg: 1.0,
          count: 1,
          token_cost: 25,
          use_consistency_default: true,
          allow_llm_prompt_polish: true,
        },
        outfit_prop: {
          endpoint_id: 'flux-portrait',
          width: 1024,
          height: 1024,
          steps: 18,
          cfg: 1.0,
          count: 4,
          token_cost: 0,
          use_consistency_default: false,
          allow_llm_prompt_polish: true,
        },
        shop_item: {
          endpoint_id: 'flux-portrait',
          width: 1024,
          height: 1024,
          steps: 16,
          cfg: 1.0,
          count: 4,
          token_cost: 0,
          use_consistency_default: false,
          allow_llm_prompt_polish: true,
        },
        admin_batch: {
          endpoint_id: 'flux-portrait',
          width: 832,
          height: 1216,
          steps: 18,
          cfg: 1.0,
          count: 1,
          token_cost: 0,
          use_consistency_default: false,
          allow_llm_prompt_polish: false,
        },
      },
    },
    language: {
      enabled: true,
      default_locale: 'en',
      fallback_locale: 'en',
      supported_locales: ['en', 'zh', 'ja', 'ko', 'es', 'fr', 'de', 'pt', 'ru'],
      force_reply_language: true,
      auto_detect: true,
      reply_instructions: {
        en:
          'LANGUAGE LOCK (this turn): User message is English. Reply in natural modern English ONLY. ' +
          'Do not use any Chinese characters (汉字). Do not switch to Chinese/Japanese/Korean. ' +
          'Do not bilingual-mix. International/Nordic English is fine.',
        zh:
          '语言锁定（本轮）：用户用中文写消息。请只用自然流畅的简体中文回复。' +
          '禁止整段英文，禁止中英夹杂乱入。动作旁白可用*星号*，对白必须是中文。',
        ja: '言語ロック：ユーザーは日本語です。自然な日本語のみで返答。中国語・英語の本文混入禁止。',
        ko: '언어 잠금: 사용자가 한국어로 썼습니다. 자연스러운 한국어로만 답하세요. 중국어/영어 본문 혼입 금지.',
        es: 'BLOQUEO DE IDIOMA: el usuario escribió en español. Responde solo en español natural. Sin chino ni bloques de inglés al azar.',
        fr: 'VERROUILLAGE LANGUE : l’utilisateur a écrit en français. Réponds uniquement en français naturel. Pas de chinois ni d’anglais mélangé.',
        de: 'SPRACHSPERRE: Der Nutzer schrieb auf Deutsch. Antworte nur auf natürlichem Deutsch. Kein Chinesisch, kein wildes Englisch-Mix.',
        pt: 'BLOQUEIO DE IDIOMA: o usuário escreveu em português. Responda só em português natural. Sem chinês nem inglês misturado.',
        ru: 'ЯЗЫКОВОЙ ЗАМОК: пользователь написал по-русски. Отвечай только на естественном русском. Без китайского и случайного английского.',
      },
    },
  };
}
