worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 2048;
}

http {
    access_log /dev/stdout;
    error_log /dev/stderr warn;

    proxy_http_version 1.1;
    proxy_buffering off;
    proxy_read_timeout 900s;
    proxy_send_timeout 900s;

    server {
        listen 80;
        server_name _;

        location = /ping {
            proxy_pass http://127.0.0.1:8000/health;
        }

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://127.0.0.1:8000;
        }
    }
}
