#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────
# hash-loras.sh — 在挂载真实网络卷的 RunPod Pod 上计算 LoRA SHA256
#
# 用法（Pod 终端）：
#   chmod +x scripts/runpod/hash-loras.sh
#   scripts/runpod/hash-loras.sh
#
# 输出清单（默认）：
#   /runpod-volume/models/loras/soulmate-lora-hashes.txt
#   每行格式：filename|sha256|size_bytes
#
# 将该清单下载回本地后运行回填工具：
#   node scripts/backfill-lora-sha256.mjs <清单路径>
#
# 环境变量：
#   VOLUME_ROOT  卷根目录（默认 /runpod-volume）
#   LORA_DIR     LoRA 目录（默认 $VOLUME_ROOT/models/loras）
#   OUTPUT       清单输出路径（默认 $LORA_DIR/soulmate-lora-hashes.txt）
# ─────────────────────────────────────────────────────────────────
set -euo pipefail

VOLUME_ROOT="${VOLUME_ROOT:-/runpod-volume}"
LORA_DIR="${LORA_DIR:-$VOLUME_ROOT/models/loras}"
OUTPUT="${OUTPUT:-$LORA_DIR/soulmate-lora-hashes.txt}"

if [[ ! -d "$LORA_DIR" ]]; then
  echo "[error] LoRA directory not found: $LORA_DIR" >&2
  echo "        请确认在挂载了真实网络卷的 RunPod Pod 中执行。" >&2
  exit 1
fi

command -v sha256sum >/dev/null 2>&1 || {
  echo "[error] sha256sum not available on this host" >&2
  exit 1
}

mapfile -t files < <(find "$LORA_DIR" -maxdepth 1 -type f -name '*.safetensors' -printf '%f\n' | sort)
if [[ ${#files[@]} -eq 0 ]]; then
  echo "[error] No .safetensors files found in $LORA_DIR" >&2
  exit 1
fi

echo "[hash] ${#files[@]} LoRA file(s) in $LORA_DIR"
tmp="${OUTPUT}.tmp"
{
  echo "# soulmate-lora-hashes — generated by scripts/runpod/hash-loras.sh"
  echo "# format: filename|sha256|size_bytes"
  echo "# generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$tmp"

i=0
for name in "${files[@]}"; do
  i=$((i + 1))
  path="$LORA_DIR/$name"
  size="$(stat -c%s "$path")"
  if [[ "$size" -eq 0 ]]; then
    echo "[skip] $name is 0 bytes (failed download?)" >&2
    continue
  fi
  echo "[hash] ($i/${#files[@]}) $name ($(numfmt --to=iec "$size" 2>/dev/null || echo "${size}B"))"
  sha="$(sha256sum "$path" | awk '{print toupper($1)}')"
  echo "${name}|${sha}|${size}" >> "$tmp"
done

mv "$tmp" "$OUTPUT"
echo "[ok] Hash manifest written to $OUTPUT ($(grep -cv '^#' "$OUTPUT") entries)"
cat "$OUTPUT"
